# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14699cb663a264919b7fba00ac1a994762403b1bb4ca5306fd781d7fee84413c3fbeffc4ac20ee9d21454ab2f6b1d222f5b85fbb841aa58e67bfcbf7d946bf97

test:
  secret_key_base: ccc87dffcf85c05d282435e2d0fb0515ae69ba9f0f62eec8bd31457f478038e4f49ae690109abef151d76707c5ad612c8b6bded7156d04c7df24e549f796fab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
